[build]
build-stage = 1
target = ["x86_64-unknown-none"]  

[target.x86_64-unknown-none.json]  
rustflags = "-C link-arg=-T../bootloader/linker.ld -C panic=abort"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]