[build]
target = ["x86_64-unknown-none"]

[net]
offline = true

[target.x86_64-unknown-none]
linker = "ld"
rustflags = [
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
    "-C", "panic=abort",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]