[build]
target = ["x86_64-unknown-none"]

[target.x86_64-unknown-none]  
rustflags = [
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
    "-C", "panic=abort"   
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]