[package]
name = "anasos-kernel"
version = "1.1.0"
authors = ["Emil Momchev <emil@momchev.dev>"]
edition = "2021"

build = "build.rs"

[dependencies]
volatile = "0.2.6"
spin = "0.9.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
