name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with GitHub
        uses: actions/checkout@v2

      - name: Install additional dependencies
        run: |
          apt-get update
          apt-get install -y nasm grub-pc-bin grub-common
          rustup target add x86_64-unknown-none

      - name: Build project
        run: make no-run

      - name: Archive build output
        run: |
          zip -r AnasOS.iso.zip AnasOS.iso

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: AnasOS.iso.zip
          path: AnasOS.iso.zip