name: Tests

on:
  push:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install additional dependencies
      run: ./install_dependencies.sh

    - name: Run Tests
      run: make test
